---
- hosts: all
  connection: local
  become: sudo

  roles:
    - common
    - fail2ban
    - ferm
    - ssmtp
    - php
    - memcached
    - mariadb
    - nginx
    - wp-cli
    - { role: sites, enviro: php, tags: [ 'sites' ] }
