---
nginx_path: /etc/nginx
nginx_logs_root: /var/log/nginx
nginx_user: www-data
nginx_fastcgi_buffers: 8 8k
nginx_fastcgi_buffer_size: 8k
nginx_ssl_path: "{{ nginx_path }}/ssl"

# HSTS defaults
#nginx_hsts_max_age: 31536000
#nginx_hsts_include_subdomains: true
#nginx_hsts_preload: true

# Fastcgi cache params
# nginx_cache_path: /var/cache/nginx
nginx_cache_path: "{{ www_root }}/{{ inventory_hostname }}/cache/nginx"
nginx_cache_duration: 30s
nginx_cache_key_storage_size: 10m
nginx_cache_size: 250m
nginx_cache_inactive: 1h
nginx_skip_cache_uri: /wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml|/store.*|/cart.*|/my-account.*|/checkout.*|/addons.*|/ideas.*
nginx_skip_cache_cookie: comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in


nginx_conf_path: /etc/nginx/nginx.conf
nginx_lib_path: /var/lib/nginx
nginx_lock_file: /var/lock/nginx.lock
nginx_log_path: /var/log/nginx
nginx_pid_file: /run/nginx.pid
nginx_prefix: /usr/local
nginx_bin: "{{ nginx_prefix }}/sbin/nginx"

nginx_build_options:
  with-http_gzip_static_module:
  with-http_realip_module:
  with-http_stub_status_module:
  with-ipv6:
  with-pcre-jit:
nginx_pagespeed_version: 1.11.33.2
nginx_user: www-data
nginx_version: 1.10.1
nginx_worker_processes: 2
nginx_pagespeed_enabled: false
